basePath: /
definitions:
  domainhandler.DomainCreateRequest:
    properties:
      base_price_per_identifier:
        minimum: 1
        type: integer
      default_ttl:
        minimum: 1
        type: integer
      domain:
        type: string
      status:
        enum:
        - active
        - inactive
        type: string
    required:
    - base_price_per_identifier
    - default_ttl
    - domain
    - status
    type: object
  domainhandler.DomainCreateResponse:
    properties:
      id: {}
    type: object
  domainhandler.DomainGetResponse:
    properties:
      base_price_per_identifier:
        type: integer
      default_ttl:
        type: integer
      domain:
        type: string
      status:
        type: string
    type: object
  pkg.ResponseDto:
    properties:
      data: {}
      error:
        $ref: '#/definitions/validator.Varror'
      message:
        type: string
      success:
        type: boolean
    type: object
  validator.ValidationError:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
  validator.Varror:
    properties:
      error:
        type: string
      validation_errors:
        items:
          $ref: '#/definitions/validator.ValidationError'
        type: array
    type: object
host: localhost:8080
info:
  contact:
    email: hi@dezh.tech
    name: API Support
    url: http://www.dezh.tech/
  description: Panda is a NOSTR NIP-05 management service developed by Dezh.tech (Dezh
    technologies).
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Panda Swagger
  version: "1.0"
paths:
  /domains:
    get:
      consumes:
      - application/json
      description: Get a list of all domains with their attributes.
      produces:
      - application/json
      responses:
        "200":
          description: Domains retrieved successfully
          schema:
            allOf:
            - $ref: '#/definitions/pkg.ResponseDto'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/domainhandler.DomainGetResponse'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.ResponseDto'
      summary: Retrieve all domains
      tags:
      - domains
    post:
      consumes:
      - application/json
      description: Create a new domain with the specified attributes.
      parameters:
      - description: Domain creation payload
        in: body
        name: domain
        required: true
        schema:
          $ref: '#/definitions/domainhandler.DomainCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Domain created successfully
          schema:
            allOf:
            - $ref: '#/definitions/pkg.ResponseDto'
            - properties:
                data:
                  $ref: '#/definitions/domainhandler.DomainCreateResponse'
              type: object
        "400":
          description: Bad Request - Validation error
          schema:
            $ref: '#/definitions/pkg.ResponseDto'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.ResponseDto'
      summary: Create a new domain
      tags:
      - domains
swagger: "2.0"
